SELECT
DMTRANSTYPE.GRTRDESCRIPTIONGROUP AS Trans_Type,
DMTRANSTYPE.GRTRDESCRIPTIONTYPE AS Trans_Detail,
FDTRANSACTIONS.GRTXRECORD_SOURCE AS Sales_Detail,
SUM((FDTRANSACTIONS.GRTXRETAIL_UNIT)) AS Retail_Units,
SUM((FDTRANSACTIONS.GRTXNONRETAIL_UNIT)) AS Non_Retail_Units,
SUM((FDTRANSACTIONS.GRTXOTHER_UNIT)) AS Units,
SUM((FDTRANSACTIONS.GRTXRETAILQUANTITY)) AS Items,
SUM((FDTRANSACTIONS.GRTXGROSS_SALES_REP_HOME)) AS Gross_Sales_Home,
SUM((FDTRANSACTIONS.GRTXNET_SALES_REP_HOME)) AS Net_Sales_Home,
SUM((FDTRANSACTIONS.GRTXDISCOUNT_REP_HOME)) AS Deductions_Home,
SUM((FDTRANSACTIONS.GRTXFRAME_COST_REP_HOME)) AS Sales_Cost_Home,
SUM((FDTRANSACTIONS.GRTXINTERNAL_COST_REP_HOME)) AS Internal_Sales_Cost_Home,
sum((FDTRANSACTIONS.GRTXTAX_REP_HOME)) AS Tax_Home,
sum((FDTRANSACTIONS.GRTXTENDER_REP_HOME)) AS Tender_Amount_Home,
sum((
CASE
WHEN (
FDTRANSACTIONS.GRTXRECORDQUALIFIER = 1100
AND (
FDTRANSACTIONS.GRTXRETAIL_UNIT != 0
OR FDTRANSACTIONS.GRTXNONRETAIL_UNIT != 0
)
)
THEN (
FDTRANSACTIONS.GRTXFRAME_GROSS_SALES_REP_HOME * FDTRANSACTIONS.
GRTXRETAIL_UNIT
)
ELSE 0
END
)) AS Calc1,
SUM((FDTRANSACTIONS.GRTXGROSS_SALES_REP_HOME_PY)) AS Gross_Sales_Home_LY_Exchange_Rate,
SUM((FDTRANSACTIONS.GRTXNET_SALES_REP_HOME_PY)) AS Net_Sales_Home_LY_Exchange_Rate,
SUM((FDTRANSACTIONS.GRTXDISCOUNT_REP_HOME_PY)) AS Deductions_Home_LY_Exchange_Rate,
DMSITE.GRCUKUNNR_INT AS Store_Num,
DMFISCCAL.GRFCDATE AS Date,
FDTRANSACTIONS.GRTXZZ_ASSOC_CUST_ID AS Customer_Num,
to_number(AL_DMTRANSACTIONS.GRTXTRANSNUMBER, '99999999999999999999') AS Transaction_Num,
DMARTICLE.GRMAL2_COMMODITY_DESCR AS Commodity_Name,
DMARTICLE.GRMAL3_CATEGORY_DESCR AS Category_Name,
DMARTICLE.GRMAL4_CLASS_DESCR AS Subcategory,
DMARTICLE.GRMAL5_MERCHANDISE_DESCR AS Merch_Group_Desc,
DMARTICLE.GRMAZZ_COLLECTION AS Collection,
ltrim(DMARTICLE.GRMAMATNR, '0') AS Article,
DMARTICLE.GRMAL7_VARIANT_DESCR AS Article_Desc,
AL_CUSTOMER_TYPE.GRD1ATYTX AS Deduction_Discount_Level,
AL_CUSTOMER_TYPE.GRD1AKTYP AS Deduction_Dicount_Level_Code,
AL_CUSTOMER_TYPE.GRD1ARTTX AS Deduction_Detail,
AL_CUSTOMER_TYPE.GRD1AKART AS Deduction_Detail_Code,
ltrim(AL_CUSTOMER_TYPE.GRD1BBYNR, 'D') AS Deduction_Code,
AL_CUSTOMER_TYPE.GRD1BBYTEXT AS Deduction_Name,
DMARTICLE.GRMATREATMENT_POLARIZED_DESC AS Treatment_Polarized_Desc,
DMTENDERTYPE.GRTETENDERTYPECODE          AS GRTETENDERTYPECODE,
DMTENDERTYPE.GRTEDESCRIPTIONTYPE         AS GRTEDESCRIPTIONTYPE
FROM
DMDISCOUNT AL_CUSTOMER_TYPE
INNER JOIN FDTRANSACTIONS
ON (FDTRANSACTIONS.GRTXCUSTOMER_TYPE = AL_CUSTOMER_TYPE.GRD1BBYNR_LPAD)
INNER JOIN DMSITE
ON (DMSITE.GRCUKUNNR = FDTRANSACTIONS.GRTXRETAILSTOREID)
INNER JOIN DMSITE_SALESORG_DISTRCHAN
ON (
DMSITE.GRCUVKORG = DMSITE_SALESORG_DISTRCHAN.GRGHVKORG
AND DMSITE.GRCUVTWEG = DMSITE_SALESORG_DISTRCHAN.GRGHVTWEG
)
INNER JOIN DMFISCCAL
ON (FDTRANSACTIONS.GRTXBUSINESSDAYDATE = DMFISCCAL.GRFCDATE)
INNER JOIN DMARTICLE
ON (DMARTICLE.GRMAMATNR = FDTRANSACTIONS.GRTXMATERIALNUMBER)
INNER JOIN DMTRANSTYPE
ON (FDTRANSACTIONS.GRTXTRANSTYPECODE = DMTRANSTYPE.GRTRTRANSTYPCODE)
INNER JOIN FDTRANSACTIONS AL_DMTRANSACTIONS
ON (
FDTRANSACTIONS.GRTXTRANSACTION_ID = AL_DMTRANSACTIONS.GRTXTRANSACTION_ID
AND FDTRANSACTIONS.GRTXTRANSACTION_ROW = AL_DMTRANSACTIONS.GRTXTRANSACTION_ROW
AND FDTRANSACTIONS.GRTXRETAILSTOREID = AL_DMTRANSACTIONS.GRTXRETAILSTOREID
)
LEFT JOIN DMTENDERTYPE
ON         (
GRTETENDERTYPECODE = SUBSTR(FDTRANSACTIONS.GRTXROWITEMTYPE, 2, 4)
AND
SUBSTR(FDTRANSACTIONS.GRTXROWITEMTYPE, 1, 1) = 'T'
)
WHERE
(
DMSITE_SALESORG_DISTRCHAN.GRGHENTITY IN (
'SGH CN',
'SGH US'
)
--                                                                            
AND FDTRANSACTIONS.GRTXBUSINESSDAYDATE BETWEEN '2014-01-12' AND '2015-01-20'

AND GRMAL7_VARIANT_DESCR <> 'Unknown'
)
GROUP BY
DMTRANSTYPE.GRTRDESCRIPTIONGROUP,
DMTRANSTYPE.GRTRDESCRIPTIONTYPE,
FDTRANSACTIONS.GRTXRECORD_SOURCE,
DMSITE.GRCUKUNNR_INT,
DMFISCCAL.GRFCDATE,
FDTRANSACTIONS.GRTXZZ_ASSOC_CUST_ID,
to_number(AL_DMTRANSACTIONS.GRTXTRANSNUMBER, '99999999999999999999'),
DMARTICLE.GRMAL2_COMMODITY_DESCR,
DMARTICLE.GRMAL3_CATEGORY_DESCR,
DMARTICLE.GRMAL4_CLASS_DESCR,
DMARTICLE.GRMAL5_MERCHANDISE_DESCR,
DMARTICLE.GRMAZZ_COLLECTION,
ltrim(DMARTICLE.GRMAMATNR, '0'),
DMARTICLE.GRMAL7_VARIANT_DESCR,
AL_CUSTOMER_TYPE.GRD1ATYTX,
AL_CUSTOMER_TYPE.GRD1AKTYP,
AL_CUSTOMER_TYPE.GRD1ARTTX,
AL_CUSTOMER_TYPE.GRD1AKART,
ltrim(AL_CUSTOMER_TYPE.GRD1BBYNR, 'D'),
AL_CUSTOMER_TYPE.GRD1BBYTEXT,
DMARTICLE.GRMATREATMENT_POLARIZED_DESC,
DMTENDERTYPE.GRTETENDERTYPECODE,
DMTENDERTYPE.GRTEDESCRIPTIONTYPE